DROP TABLE IF EXISTS WIDGET;

CREATE TABLE WIDGET (
  widget_id INTEGER PRIMARY KEY,
  code varchar(26) NOT NULL UNIQUE,
  name VARCHAR(64) NOT NULL,
  num_parts INTEGER NOT NULL,
  created_at INTEGER(4) NOT NULL DEFAULT (datetime()),
  updated_at INTEGER(4) NULL
)
;

DROP TRIGGER IF EXISTS UPDATE_WIDGET_TRIGGER;

CREATE TRIGGER UPDATE_WIDGET_TRIGGER
AFTER UPDATE ON WIDGET
BEGIN
  UPDATE WIDGET SET updated_at = datetime() WHERE widget_id = NEW.widget_id;
END;
