DROP TABLE IF EXISTS WIDGETS;

CREATE TABLE WIDGETS (
  widget_id INTEGER PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  description VARCHAR(256) NULL,
  num_parts INTEGER NOT NULL,
  created_at INTEGER(4) NOT NULL DEFAULT (datetime()),
  updated_at INTEGER(4) NULL
)
;

DROP TRIGGER IF EXISTS UPDATE_WIDGET_TRIGGER;

CREATE TRIGGER UPDATE_WIDGET_TRIGGER
AFTER UPDATE ON WIDGETS
BEGIN
  UPDATE WIDGETS SET updated_at = datetime() WHERE widget_id = NEW.widget_id;
END;
